{email: state.email, name: "Raza Anis", password: "abc123", nextPath:"get-test-2018-1", accuracy: "57", totalMcqs: "400", recentPackages: [{name: "GET TEST 2018", path: "get-test-2018-1"}],
              posts: [{
                id: 1,
                poster: "Admin",
                dated: "1-01-2019",
                title: "New Annoucement",
                description: "Somewhat long statement",
                userpic: "https://gs-post-images.grdp.co/2018/6/gate-img1529910709846-84.png-rs-high-webp.png",
              }],
              courses: [
                {
                  id: 1,
                  name: "GET TEST 2018",
                  price: "180",
                  currency: "USD",
                  availability: "released",
                  description: "Some long description about this particular course",
                  mcqQuantity: 100,
                  duration: 3,
                  timeOver: false,
                  inCart: false,
                  path: "get-test-2018",
                  imgSrc: "https://gs-post-images.grdp.co/2018/6/gate-img1529910709846-84.png-rs-high-webp.png",
                  tests: [
                    {
                      id: 1,
                      name: "Test 1 2018",
                      duration: 2,
                      mcqQuantity: 5,
                      availability: "released",
                      passRequirementPercentage: 50,
                      lastTakenDate: "12-08-2018",
                      lastScore: "0.0",
                      path: "get-test-2018-1",
                      lastCorrect: 20,
                      lastIncorrect: 90,
                      lastStoredDataReview: [{
                        id: 1,
                        title: "Programming Language",
                        question: "Which is the best Programming Language? ",
                        answer1: "Python",
                        answer2: "Java",
                        answer3: "JavaScript",
                        answer4: "All of these",
                        truthyOption: "4",
                        selectedAnswer: 4,
                      },
                      {
                        id: 2,
                        title: "Programming Language 2",
                        question: "Which is the best Programming Language? ",
                        answer1: "Python",
                        answer2: "Java",
                        answer3: "JavaScript",
                        answer4: "All of these",
                        truthyOption: "2",
                        selectedAnswer: 2,
                      },
                      {
                        id: 3,
                        title: "Programming Language 3",
                        question: "Which is the best Programming Language? ",
                        answer1: "Python",
                        answer2: "Java",
                        answer3: "JavaScript",
                        answer4: "All of these",
                        truthyOption: "3",
                        selectedAnswer:3,
                      },
                      {
                        id: 4,
                        title: "Programming Language 3",
                        question: "Which is the best Programming Language? ",
                        answer1: "Python",
                        answer2: "Java",
                        answer3: "JavaScript",
                        answer4: "All of these",
                        truthyOption: "3",
                        selectedAnswer: 1,
                      },
                      {
                        id: 5,
                        title: "Programming Language 3",
                        question: "Which is the best Programming Language? ",
                        answer1: "Python",
                        answer2: "Java",
                        answer3: "JavaScript",
                        answer4: "All of these",
                        truthyOption: "3",
                        selectedAnswer: 2,
                      }],
                      attemptedBy: 30,
                      questions: [{
                        id: 1,
                        title: "Programming Language",
                        question: "Which is the best Programming Language? ",
                        answer1: "Python",
                        answer2: "Java",
                        answer3: "JavaScript",
                        answer4: "All of these",
                        truthyOption: "4",
                        selectedAnswer: 0,
                      },
                      {
                        id: 2,
                        title: "Programming Language 2",
                        question: "Which is the best Programming Language? ",
                        answer1: "Python",
                        answer2: "Java",
                        answer3: "JavaScript",
                        answer4: "All of these",
                        truthyOption: "2",
                        selectedAnswer: 0,
                      },
                      {
                        id: 3,
                        title: "Programming Language 3",
                        question: "Which is the best Programming Language? ",
                        answer1: "Python",
                        answer2: "Java",
                        answer3: "JavaScript",
                        answer4: "All of these",
                        truthyOption: "3",
                        selectedAnswer: 0,
                      },
                      {
                        id: 4,
                        title: "Programming Language 3",
                        question: "Which is the best Programming Language? ",
                        answer1: "Python",
                        answer2: "Java",
                        answer3: "JavaScript",
                        answer4: "All of these",
                        truthyOption: "3",
                        selectedAnswer: 0,
                      },
                      {
                        id: 5,
                        title: "Programming Language 3",
                        question: "Which is the best Programming Language? ",
                        answer1: "Python",
                        answer2: "Java",
                        answer3: "JavaScript",
                        answer4: "All of these",
                        truthyOption: "3",
                        selectedAnswer: 0,
                      }]
                    },
                    {
                      id: 1,
                      name: "Test 1 2018",
                      duration: 2,
                      mcqQuantity: 5,
                      availability: "upcoming",
                      passRequirementPercentage: 50,
                      lastTakenDate: "12-08-2018",
                      lastScore: "0.0",
                      path: "get-test-2018-1",
                      lastCorrect: 20,
                      lastIncorrect: 90,
                      lastStoredDataReview: [{
                        id: 1,
                        title: "Programming Language",
                        question: "Which is the best Programming Language? ",
                        answer1: "Python",
                        answer2: "Java",
                        answer3: "JavaScript",
                        answer4: "All of these",
                        truthyOption: "4",
                        selectedAnswer: 4,
                      },
                      {
                        id: 2,
                        title: "Programming Language 2",
                        question: "Which is the best Programming Language? ",
                        answer1: "Python",
                        answer2: "Java",
                        answer3: "JavaScript",
                        answer4: "All of these",
                        truthyOption: "2",
                        selectedAnswer: 2,
                      },
                      {
                        id: 3,
                        title: "Programming Language 3",
                        question: "Which is the best Programming Language? ",
                        answer1: "Python",
                        answer2: "Java",
                        answer3: "JavaScript",
                        answer4: "All of these",
                        truthyOption: "3",
                        selectedAnswer:3,
                      },
                      {
                        id: 4,
                        title: "Programming Language 3",
                        question: "Which is the best Programming Language? ",
                        answer1: "Python",
                        answer2: "Java",
                        answer3: "JavaScript",
                        answer4: "All of these",
                        truthyOption: "3",
                        selectedAnswer: 1,
                      },
                      {
                        id: 5,
                        title: "Programming Language 3",
                        question: "Which is the best Programming Language? ",
                        answer1: "Python",
                        answer2: "Java",
                        answer3: "JavaScript",
                        answer4: "All of these",
                        truthyOption: "3",
                        selectedAnswer: 2,
                      }],
                      attemptedBy: 30,
                      questions: [{
                        id: 1,
                        title: "Programming Language",
                        question: "Which is the best Programming Language? ",
                        answer1: "Python",
                        answer2: "Java",
                        answer3: "JavaScript",
                        answer4: "All of these",
                        truthyOption: "4",
                        selectedAnswer: 0,
                      },
                      {
                        id: 2,
                        title: "Programming Language 2",
                        question: "Which is the best Programming Language? ",
                        answer1: "Python",
                        answer2: "Java",
                        answer3: "JavaScript",
                        answer4: "All of these",
                        truthyOption: "2",
                        selectedAnswer: 0,
                      },
                      {
                        id: 3,
                        title: "Programming Language 3",
                        question: "Which is the best Programming Language? ",
                        answer1: "Python",
                        answer2: "Java",
                        answer3: "JavaScript",
                        answer4: "All of these",
                        truthyOption: "3",
                        selectedAnswer: 0,
                      },
                      {
                        id: 4,
                        title: "Programming Language 3",
                        question: "Which is the best Programming Language? ",
                        answer1: "Python",
                        answer2: "Java",
                        answer3: "JavaScript",
                        answer4: "All of these",
                        truthyOption: "3",
                        selectedAnswer: 0,
                      },
                      {
                        id: 5,
                        title: "Programming Language 3",
                        question: "Which is the best Programming Language? ",
                        answer1: "Python",
                        answer2: "Java",
                        answer3: "JavaScript",
                        answer4: "All of these",
                        truthyOption: "3",
                        selectedAnswer: 0,
                      }]
                    }

                  ]
                }
              ]
              }
      		 	}


            {"id":1,"name":"GET TEST 2018","price":"180","currency":"USD","availability":"released","description":"Some long description about this particular course","mcqQuantity":100,"duration":3,"inCart":true,"path":"/about","imgSrc":"https://gs-post-images.grdp.co/2018/6/gate-img1529910709846-84.png-rs-high-webp.png"}
